apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  PGHOST: {{ .Values.database.host | quote }}
  PGPORT: {{ .Values.database.port | quote }}
  PGDATABASE: {{ .Values.database.name | quote }}
  PGUSER: {{ .Values.database.user | quote }} 