apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGPASSWORD: {{ .Values.database.password | quote }}